on:
  push:
    branches:
      - master
name: Deploy
jobs:
  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set output
        id: vars
        run: echo ::set-output name=sha::${GITHUB_SHA}

      - name: Docker publish
        uses: daspawnw/docker-multi-build-push-action@master
        with:
          docker-tag: "${{ steps.vars.outputs.sha }}"
          ghcr-enabled: "true"
          ghcr-token: "${{ secrets.GITHUB_TOKEN }}"
          ecr-enabled: "false"